name: 'Sorald Buildbreaker'
description: 'Run Sorald and break the build if there are any repairable violations'
inputs:
  source:
    description: 'Path to the root source code directory to analyze'
    required: true
    default: '.'
  sorald-jar-url:
    description: 'URL to a Sorald JAR-file'
    required: true
    default: 'https://oss.sonatype.org/service/local/repositories/releases/content/se/kth/castor/sorald/0.2.0/sorald-0.2.0.jar'
runs:
  using: 'node12'
  main: 'dist/index.js'
