name: 'Sorald Buildbreaker'
description: 'Run Sorald and break the build if there are any repairable violations'
inputs:
  source:
    description: 'Path to the root source code directory to analyze'
    required: true
    default: '.'
  ratchet-from:
    description: 'Commit-ish to ratchet from, typically origin/master or origin/main)'
    required: false
  post-review-comments:
    description: 'If true and the commenter bot is installed, repairs are posted as review comments on pull requests'
    required: false
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
