name: 'Sorald Buildbreaker'
description: 'Run Sorald and break the build if there are any repairable violations'
inputs:
  source:
    description: 'Path to the root source code directory to analyze'
    required: true
    default: '.'
  sorald-jar-url:
    description: 'URL to a Sorald JAR-file'
    required: true
    default: 'https://github.com/SpoonLabs/sorald/releases/download/sorald-0.2.0/sorald-0.2.0-jar-with-dependencies.jar'
  ratchet-from:
    description: 'Commit-ish to ratchet from, typically origin/master or origin/main)'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
