name: 'Sorald Buildbreaker'
description: 'Run Sorald and break the build if there are any repairable violations'
inputs:
  source:
    description: 'Path to the root source code directory to analyze'
    required: true
    default: '.'
  ratchet-from:
    description: 'Commit-ish to ratchet from, typically origin/master or origin/main)'
    required: false
  token:
    description: 'Token to post comments with'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
