name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2 # required for Codecov to be able to identify the commit
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: |
          npm install
      - name: Configure Git user
        run: |
          git config --global user.name Tester
          git config --global user.email tester@spoonlabs.github.io
      - run: |
          npm run all
      - name: Check generated files are up-to-date
        run: git diff --exit-code
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@a1ed4b322b4b38cb846afb5a0ebfa17086917d27 # v1.5.0
        with:
          fail_ci_if_error: true
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          source: src/
