# Workflow to update generated files on pull requests

name: update-generated-files

on:
  pull_request:

jobs:
  update-generated-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: npm install
      - name: Configure Git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: |
          npm run build
          npm run package
      - name: Push generated files updates
        if: success()
        run: |
          git diff --exit-code || {
            git commit -am 'Update generated files'
            git push origin "HEAD:$GITHUB_HEAD_REF"
          }
